# Generated by Django 4.0.3 on 2022-07-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=25)),
                ('empsalary', models.IntegerField()),
                ('empAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
